# Site settings
title: Learn Meteor With Dan
description: >
  Follow me as I learn how to make a full featured meteor site with mobile apps. 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hiaw.github.io" # the base hostname & protocol for your site

author:
  fullname: Daniel Chong
  googleplus: https://www.google.com/+MotaquillahMaddane
  github: hiaw
  twitter: hiaw
  linkedin: danielgqchong
  email: danielgq.chong@gmail.com
  disqus: learmeteor

google_analytics: 'UA-70443160-1'

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap